// Beat 3 — turn a reviewer's decision into a signed, tamper-evident PDF
// record and a ledger row. Server-only (filesystem + DWS).
import { createHash } from "node:crypto";
import { ensureRun } from "../data/live";
import type { AuditRecord, Finding, RejectReason } from "../data/types";
import { renderPdf, signRecord } from "../nutrient";
import { currentReviewer, SAMPLE_REVIEW } from "./bundle";
import {
  appendLedger,
  assertSafeId,
  deleteRecordPdf,
  removeLedger,
  saveRecordPdf,
} from "./store";

export const REJECT_REASONS: readonly RejectReason[] = [
  "not_a_conflict",
  "extraction_error",
  "immaterial",
  "resolved_elsewhere",
];

export function isRejectReason(value: unknown): value is RejectReason {
  return typeof value === "string" && (REJECT_REASONS as readonly string[]).includes(value);
}

export interface SignInput {
  reviewId: string;
  flagId: string;
  decision: "approved" | "rejected";
  reason?: RejectReason;
  note?: string;
  reviewer?: string;
}

export class SignError extends Error {
  status: number;
  constructor(message: string, status: number) {
    super(message);
    this.status = status;
  }
}

/** Denormalized claim context for the ledger, read off the finding union. */
export function ledgerContext(finding: Finding): {
  field: string;
  value: string;
  evidence: string;
} {
  switch (finding.verdict) {
    case "conflicting":
      return {
        field: finding.flag.field,
        value: `${finding.flag.claimA.value} vs ${finding.flag.claimB.value}`,
        evidence: `Cross-document: ${finding.sourceA.documentId} p.${finding.sourceA.page} vs ${finding.sourceB.documentId} p.${finding.sourceB.page} · ${finding.deltaLabel}`,
      };
    case "stale":
      return {
        field: finding.flag.claim.field,
        value: `${finding.flag.claim.value} vs ${finding.flag.liveValue}`,
        evidence: `Live check: ${finding.flag.query} · ${finding.flag.liveSourceUrl ?? "no source URL recorded"}`,
      };
    default:
      return {
        field: finding.claim.field,
        value: finding.claim.value,
        evidence: `${finding.source.documentId} p.${finding.source.page}${finding.note ? ` · ${finding.note}` : ""}`,
      };
  }
}

/** Escape the few characters that would break a Markdown table cell. */
function cell(text: string | undefined): string {
  return (text ?? "—").replace(/\|/g, "\\|").replace(/\s+/g, " ").trim() || "—";
}

export function recordMarkdown(input: {
  reviewId: string;
  reviewTitle: string;
  finding: Finding;
  decision: SignInput["decision"];
  reviewer: string;
  signedAt: string;
  reason?: RejectReason;
  note?: string;
}): string {
  const ctx = ledgerContext(input.finding);
  return `# Sparkline review record

**Review:** ${input.reviewTitle} (${input.reviewId})

**Finding:** ${input.finding.label} — ${input.finding.verdict.replace("_", " ")} · ${input.finding.materiality}

**Decision:** ${input.decision.toUpperCase()}

**Reviewer:** ${input.reviewer}

**Decided at:** ${input.signedAt}

| Field | Value |
|---|---|
| Finding id | ${cell(input.finding.id)} |
| Claim field | ${cell(ctx.field)} |
| Claim value | ${cell(ctx.value)} |
| Evidence | ${cell(ctx.evidence)} |
| Reason | ${cell(input.reason)} |
| Reviewer note | ${cell(input.note)} |

Generated by Sparkline. Extraction and the digital signature below are performed by Nutrient DWS; the signature binds this decision to this document, and any later change invalidates it.
`;
}

/**
 * Render → sign → hash → store → ledger. Returns the AuditRecord the ledger
 * now carries for this finding.
 */
export async function signDecision(input: SignInput): Promise<AuditRecord> {
  const reviewId = assertSafeId(input.reviewId, "reviewId");
  const flagId = assertSafeId(input.flagId, "flagId");
  const ensured = ensureRun(reviewId);
  if (!ensured) throw new SignError(`No review with id ${reviewId}`, 404);
  const finding = ensured.run.findings.find((f) => f.id === flagId);
  if (!finding) throw new SignError(`No finding ${flagId} in review ${reviewId}`, 404);
  if (input.decision === "rejected" && !input.reason) {
    throw new SignError("A rejection needs a reason", 400);
  }

  const reviewer =
    input.reviewer?.trim() || currentReviewer() || "an unidentified reviewer";
  const signedAt = new Date().toISOString();
  const reviewTitle = ensured.run.review.title ?? SAMPLE_REVIEW.title;

  const markdown = recordMarkdown({
    reviewId,
    reviewTitle,
    finding,
    decision: input.decision,
    reviewer,
    signedAt,
    reason: input.reason,
    note: input.note,
  });
  const unsigned = await renderPdf(markdown, `${flagId.replace(/[^A-Za-z0-9_-]+/g, "-")}.md`);
  const signed = await signRecord(unsigned);
  const contentHash = `sha256:${createHash("sha256").update(signed).digest("hex")}`;
  saveRecordPdf(reviewId, flagId, signed);

  const ctx = ledgerContext(finding);
  const record: AuditRecord = {
    flagId,
    reviewer,
    decision: input.decision,
    signedAt,
    signedDocumentUrl: `/api/records/${encodeURIComponent(reviewId)}/${encodeURIComponent(flagId)}`,
    contentHash,
    claimField: ctx.field,
    claimValue: ctx.value,
    evidenceSummary: ctx.evidence,
    ...(input.reason ? { reason: input.reason } : {}),
    ...(input.note?.trim() ? { note: input.note.trim() } : {}),
  };
  appendLedger(reviewId, record);
  return record;
}

/** Undo: drop the ledger row and the signed PDF behind it. */
export function withdrawDecision(reviewId: string, flagId: string): void {
  assertSafeId(reviewId, "reviewId");
  assertSafeId(flagId, "flagId");
  removeLedger(reviewId, flagId);
  deleteRecordPdf(reviewId, flagId);
}
